### ISSUE TITLE
`chain` service panics when validator not found, causing db `PoisonError`

### ISSUE THREAD

**Issue by iskay** [anoma/namada-indexer#129]
On the housefire chain, the `chain` service has periodically been hanging:

```
2024-10-02T13:27:33.612715Z  INFO chain: Updating bonds for 1 addresses
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/deadpool-sync-0.1.4/src/lib.rs:123:44:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
2024-10-02T13:27:33.612877Z  INFO chain: Updating unbonds for 0 addresses
2024-10-02T13:27:33.612920Z  INFO chain: Updating revealed pks for 1 addresses
2024-10-02T13:27:33.613123Z ERROR shared::error: Database error reason=Failed to interact with db
```
and
```
2024-10-03T18:10:37.606483Z  INFO chain: Inserting initial data...
thread 'tokio-runtime-worker' panicked at chain/src/repository/pos.rs:67:26:
Failed to get validator: NotFound
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-10-03T18:10:42.177576Z ERROR shared::error: Database error reason=Failed to interact with db
Error: Database
```

The query that causes the panic is
```
SELECT "validators"."id", "validators"."namada_address", "validators"."voting_power", "validators"."max_commission", "validators"."commission", "validators"."name", "validators"."email", "validators"."website", "validators"."description", "validators"."discord_handle", "validators"."avatar", "validators"."state" FROM "validators" WHERE ("validators"."namada_address" = $1) LIMIT $2
```

This behaviour can be triggered by initializing a new validator and immediately bonding tokens to it before it's active (which is possible with the CLI). The `chain` service will try to process the bond tx, but since the target validator is not yet present in the validators table it will result in a panic.

The `chain` service will panic/restart repeatedly until two epochs have passed and the validator has been added to the validators table, at which point it can proceed. This likely went unnoticed before because epochs were only 5 minutes on previous housefire chains (they are 1 hr on the latest chain).

**Comment by iskay** [comment]
A newly initialized validator is not included in the list returned by the sdk `get_all_validators` query until the `pipeline_len` has passed. However, you can still bond tokens to it during this time, and the sdk `is_validator` query returns true.

So maybe this is a bug in the sdk?

**Comment by mateuszjasiuk** [comment]
@iskay [Fix ](https://github.com/anoma/namada-indexer/pull/130)is in the queue. It does not touch the db so it should be enough to just restart services 🙏
