### ISSUE TITLE
Cannot serialize TransactionKind: Error("key must be a string", line: 0, column: 0)

### ISSUE THREAD

**Issue by alxnode** [anoma/namada-indexer#152]
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
2024-11-17T08:02:54.407279Z  INFO transactions: Attempting to process block: 47019... **or block 46977** <also had the same
2024-11-17T08:02:54.407959Z  INFO transactions: Query block...
2024-11-17T08:02:54.410591Z  INFO transactions: Raw block contains 1 txs...
2024-11-17T08:02:54.410600Z  INFO transactions: Query block results...
thread 'main' panicked at shared/src/transaction.rs:56:38:
Cannot serialize TransactionKind: Error("key must be a string", line: 0, column: 0)

**Comment by Fraccaman** [comment]
on which network?

**Comment by brentstone** [comment]
@alxnode you need to provide a lot more details for this to be a useful issue please. Include network, software version, and the full logs including the commands run and their corresponding output.

**Comment by sug0** [comment]
This error message is related with a JSON encoding failure. We attempted to serialized a map-like data structure whose keys were not strings. JSON objects only support strings as keys, hence the error.

**Comment by alxnode** [comment]
> on which network?

Namada dry run. Latest commit (80064f7c34cc2403ff8c06c5607a60cd2c23aeea)
Reported this issue without details since https://indexer.knowable.run have this issue too.
Transaction container is halted if u check it
