### ISSUE TITLE
Unable to update bonds [number of parameters must be between 0 and 65535]

### ISSUE THREAD

**Issue by alxnode** [anoma/namada-indexer#177]
number of parameters must be between 0 and 65535
    
Error: Database
2024-12-04T12:08:45.905715Z  INFO chain: Querying initial data...
2024-12-04T12:08:46.784235Z  INFO chain: Querying validators set...
2024-12-04T12:08:47.102869Z  INFO chain: Querying bonds and unbonds...
2024-12-04T12:08:47.441093Z  INFO chain: Querying proposals...
2024-12-04T12:08:47.482363Z  INFO chain: Inserting initial data... 
2024-12-04T12:08:51.654824Z ERROR shared::error: Database error reason=Failed to update bonds in db

Caused by:
    number of parameters must be between 0 and 65535
    
Error: Database
Latest commit; Namada mainnet; chain-indexer container
We need chunks if indexer running not from 0 epoch or had restart

**Comment by Fraccaman** [comment]
Thanks for bringing this up! We solved this issue in #178

**Comment by alxnode** [comment]
> Thanks for bringing this up! We solved this issue in #178

I would reopen those issue
Likely because of chunk updates bonds and unbonds are invalid
At the latest version of indexer
select * from validators where namada_address='tnam1q8xasrt0q8qrkqj5s9r9xw3ee0gx5mqwyukhe699' gonna show>907K token while actual bond is 858K
The same for many other validators
bonds table is wrong, which likely causing validators table mistake

**Comment by bombermine3** [comment]
It seems this is not fixed:
```
chain-1  | 2024-12-11T22:07:14.935140Z  INFO chain: Inserting initial data... block=101727
chain-1  | 2024-12-11T22:07:20.404305Z ERROR shared::error: Database error reason=Failed to update bonds in db
chain-1  | 
chain-1  | Caused by:
chain-1  |     number of parameters must be between 0 and 65535
chain-1  |     
chain-1  | 2024-12-11T22:07:22.082829Z  INFO chain: Inserting initial data... block=101728
chain-1  | 2024-12-11T22:07:28.019036Z ERROR shared::error: Database error reason=Failed to update bonds in db
chain-1  | 
chain-1  | Caused by:
chain-1  |     number of parameters must be between 0 and 65535
chain-1  |     
chain-1  | 2024-12-11T22:07:29.660796Z  INFO chain: Inserting initial data... block=101730
chain-1  | 2024-12-11T22:07:35.529463Z ERROR shared::error: Database error reason=Failed to update bonds in db
chain-1  | 
chain-1  | Caused by:
chain-1  |     number of parameters must be between 0 and 65535
```

**Comment by alxnode** [comment]
> @Fraccaman It seems this is not fixed:
> 
> ```
> chain-1  | 2024-12-11T22:07:14.935140Z  INFO chain: Inserting initial data... block=101727
> chain-1  | 2024-12-11T22:07:20.404305Z ERROR shared::error: Database error reason=Failed to update bonds in db
> chain-1  | 
> chain-1  | Caused by:
> chain-1  |     number of parameters must be between 0 and 65535
> chain-1  |     
> chain-1  | 2024-12-11T22:07:22.082829Z  INFO chain: Inserting initial data... block=101728
> chain-1  | 2024-12-11T22:07:28.019036Z ERROR shared::error: Database error reason=Failed to update bonds in db
> chain-1  | 
> chain-1  | Caused by:
> chain-1  |     number of parameters must be between 0 and 65535
> chain-1  |     
> chain-1  | 2024-12-11T22:07:29.660796Z  INFO chain: Inserting initial data... block=101730
> chain-1  | 2024-12-11T22:07:35.529463Z ERROR shared::error: Database error reason=Failed to update bonds in db
> chain-1  | 
> chain-1  | Caused by:
> chain-1  |     number of parameters must be between 0 and 65535
> ```

what is your commit of indexer? i double checked now and working

**Comment by bombermine3** [comment]
Apologies for the confusion. I was using the latest commit of the indexer but forgot to perform a rebuild
