### ISSUE TITLE
chain: should only do initial_query when necessary

### ISSUE THREAD

**Issue by joel-u410** [anoma/namada-indexer#179]
Currently, the `chain` indexer runs `initial_query` every time it starts up, regardless of `crawler_state` in the database. This results in a couple issues whenever the indexer process is restarted after initial run:

* `all_balances` are inserted more times than needed
* some blocks could be skipped

This can be improved, I think, by changing it as follows:

* On startup, retrieve `crawler_state` for `chain`.
* If `crawler_state` does not exist for `chain`, then do `initial_query` followed by `crawl`.
* If `crawler_state` does exist for `chain`:
    * Attempt to run `crawling_fn` for `crawler_state.last_processed_block + 1`.
    * If it succeeds, continue `crawl` without doing `initial_query`.
    * If it fails, do `initial_query` followed by `crawl`. (This can occur if the node has already pruned the `last_processed_block`).
        * (Really, we should look for a _specific_ failure to trigger an `initial_query` here: `RPC error: Cannot query more than 3600 blocks in the past (configured via shell.storage_read_past_height_limit)., error code: 1`)

I will submit a PR that implements this later today.

**Comment by mateuszjasiuk** [comment]
Yeah makes sense. Thanks!
