### ISSUE TITLE
validator's state is not updating

### ISSUE THREAD

**Issue by alxnode** [anoma/namada-indexer#185]
changing validators state from consensus>active>jailed or any other way is not working
Latest commit
https://indexer.namada.tududes.com/api/v1/pos/validator?state=consensus > 180 consensus while in fact 183
other indexers have the same issue, not only this provider
Same happens to jailed > they not updating, as well as any other changes in state

**Comment by alxnode** [comment]
only initial paste works

**Comment by Fraccaman** [comment]
Done in #205
