### ISSUE TITLE
enhancement: store block timestamps

### ISSUE THREAD

**Issue by joel-u410** [anoma/namada-indexer#189]
It'll be good to store `timestamp` for blocks along with `height` so that transactions and balances can be queried with timestamps.

I propose introducing a `blocks` table to capture that data. (Will submit a PR for this soon)

At this point, since `mainnet` has now launched, I assume we should introduce new `migrations` rather than modifying existing ones, correct? (cc @mateuszjasiuk @Fraccaman)

**Comment by Fraccaman** [comment]
Yeah, this is something @mateuszjasiuk is working on!

**Comment by joel-u410** [comment]
> Yeah, this is something @mateuszjasiuk is working on! Yeah now we need to introduce new migrations :)

Ah .. I just wrote it myself and opened a PR here: https://github.com/anoma/namada-indexer/pull/190 :)

**Comment by mateuszjasiuk** [comment]
That's fine! I should've added issue. Anyways, I think as a rule of thumb maybe we should add a label like: "ready" or sth, to indicate that issue makes sense and we do not double the work.
