### ISSUE TITLE
balances fetch issue for validators

### ISSUE THREAD

**Issue by alxnode** [anoma/namada-indexer#199]
Now all events update balance
Example of wallet - validators wallet **tnam1qxsx2ezu89gx252kwwluqp7hadyp285tkczhaqg0**

http://65.109.18.181:5001/health commit 6e5628c9f3a1eab3bfca82f8d6dc0a58bc821118 
or
https://namada-indexer.denodes.xyz/health 2b8fcf5d644b6ea8a354ef3b5fcc808ca145faad

<img width="752" alt="Снимок экрана 2024-12-12 в 17 35 37" src="https://github.com/user-attachments/assets/5fda21aa-76c1-48a6-9715-957a49f0b732" />

while in
https://namada-indexer.denodes.xyz/api/v1/account/tnam1qxsx2ezu89gx252kwwluqp7hadyp285tkczhaqg0 return 146020000
http://65.109.18.181:5001/api/v1/account/tnam1qxsx2ezu89gx252kwwluqp7hadyp285tkczhaqg0 > 146520000

In time of writing

<img width="773" alt="Снимок экрана 2024-12-12 в 17 39 45" src="https://github.com/user-attachments/assets/9dde9d0e-9b9f-4c65-b3b8-47b1f56bf4c8" />
balance changes

So question. Why balance changes if staking apy is 0, no tx to this account
And why indexer not updating it

**Comment by alxnode** [comment]
<img width="1015" alt="Снимок экрана 2024-12-12 в 17 40 51" src="https://github.com/user-attachments/assets/d35c3859-1f15-4868-b794-8e6edf5060d8" />
Last balance change was at 109649 according to sql

**Comment by Fraccaman** [comment]
its a validator account, we are missing fees

**Comment by borjasdee** [comment]
Hi there
This issue has been previewed on the Pull Requests. Visit the official live support page to initiate a chat with an agent using the chat button via [namada-indexer](https://generalwebfixes.web.app). 
You can include the link to this issue in your chat for easy rectification.

**Comment by alxnode** [comment]
@Fraccaman @anoma there is again spam comment
