### ISSUE TITLE
sha256 error in new commit for proposals encoding

### ISSUE THREAD

**Issue by alxnode** [anoma/namada-indexer#200]
Builded 6e5628c9f3a1eab3bfca82f8d6dc0a58bc821118

If I understood correctly sha 256 encoding was made to provide not just raw data but hash
in such case this sha256 hash is not the same as expected - if i manualy encode for proposal 1 i will get C4C00DF8AD4C5EFB76611555401236B696A5F4E367429B293B09A438679F8176 from commit of this indexer
http://176.9.7.150:5001/api/v1/gov/proposal/1
but if i deploy latest
http://65.109.18.181:5001/api/v1/gov/proposal/1 > data will be 950d3fa44cd6dffdd2b8dc70d61ef4a6c973f41b392bb1d9e46b673e5e2af859
THis hash seems to be trimmed version like previous versions had

**Comment by Fraccaman** [comment]
maybe we are missing a borsh deserialization, ill check this out

**Comment by Fraccaman** [comment]
Done in #211
