### ISSUE TITLE
After update to v1.0.1 balance_changes2024-12-13T11:47:38.089362Z ERROR shared::error: Database error reason=Failed to update balances in db  Caused by:     relation "balance_changes" does not exist

### ISSUE THREAD

**Issue by RuslanGlaznyov** [anoma/namada-indexer#209]
chain-indexer 

```
2024-12-13T11:48:04.182074Z ERROR shared::error: Database error reason=Failed to update balances in db

Caused by:
    relation "balance_changes" does not exist
```

**Comment by Fraccaman** [comment]
uhmmm you might need to drop your database and recreate it.

**Comment by RuslanGlaznyov** [comment]
There are changes in pev migration so I applied the old migration manually. 
https://github.com/anoma/namada-indexer/commit/718e836bb0a7e91c62731cc42bda84958ff91253#diff-3c04ac80bf67d8dbe08a6532ce366a25cb1c35fbc8db49e7375c040f8c69365dL12
