### ISSUE TITLE
Pool balances

### ISSUE THREAD

**Issue by alxnode** [anoma/namada-indexer#229]
Pool balances, like PGF, POS and so on should be updated on each height
For example, 
https://namada-api.sproutstake.space/api/v1/account/tnam1pgqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkhgajr will have old data as well as other indexers due to this issue

**Comment by alxnode** [comment]
Closing as fixed 718e836bb0a7e91c62731cc42bda84958ff91253

**Comment by alxnode** [comment]
Reopening issue since PGF balances doenst update

**Comment by Fraccaman** [comment]
Done #233
