### ISSUE TITLE
Can we try this out?

### ISSUE THREAD

**Issue by opsecx** [anoma/namada-indexer#36]
Hey guys, was given this link in discord when asking for in-house indexer. Can you confirm this can be run atm? Is it correctly understood the docker is just for hosting the db and we can provide own local db instead? Thanks

**Comment by Fraccaman** [comment]
Hi @opsecx! Yeah you can test this out! yep you can use ur own local db without docker. Let us know how it goes :) also keep in mind this is still a wip.

**Comment by opsecx** [comment]
> Hi @opsecx! Yeah you can test this out! yep you can use ur own local db without docker. Let us know how it goes :) also keep in mind this is still a wip.

Cool thanks! Is the readme matheuz made earlier that was not merged still valid for which commands to use to run the indexer?

**Comment by Fraccaman** [comment]
You can either try with the docker compose or you can run each micro-service independently by using the `run.sh` script inside each folder (chain, governance, pos, rewards, webserver)

**Comment by opsecx** [comment]
> You can either try with the docker compose or you can run each micro-service independently by using the `run.sh` script inside each folder (chain, governance, pos, rewards, webserver)

I get this weird error: `thread 'main' panicked at chain/src/main.rs:43:17:
tx_transfer.wasm must be defined in namada storage.`

not sure if because I try running it against a 31.9 rpc to index shielded expedition chain..

**Comment by Fraccaman** [comment]
ahhh no you need namada version 0.36+

**Comment by opsecx** [comment]
> ahhh no you need namada version 0.36+ 

Alright thanks. My confusion is due to us asking in the discord about the custom indexer you guys use for scoring the SE, and a link to this indexer was provided by gavin. I assume these are not the same then?
