### ISSUE TITLE
App panicks

### ISSUE THREAD

**Issue by opsecx** [anoma/namada-indexer#7]
Hi guys, trying to run this on a pre-fork 0.31.9 rpc (assume this is the way to start?). After running migrations and building chain crawler, I get the following error pretty quick:

`namada-indexer/target/debug/chain --cargo-env development --tendermint-url 'http://127.0.0.1:26657' --checksums-filepath ../artifacts/checksums.json --chain-id shielded-expedition.88f17d1d14 --database-url 'postgres://[redacted]:[redacted]@0.0.0.0:5432/[redacted]'
2024-05-09T08:13:30.061099Z INFOchain:Attempting to process block: 4...
2024-05-09T08:13:30.068009Z INFOchain:Query block...
2024-05-09T08:13:30.085953Z INFOchain:Raw block contains 200 txs...
2024-05-09T08:13:30.086016Z INFOchain:Query block results...
2024-05-09T08:13:30.124550Z INFOchain:Query epoch...
thread 'main' panicked at shared/src/transaction.rs:118:66:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

What do?

**Comment by Fraccaman** [comment]
this is not even in alpha stage, we are actively working on it. Wait for a release :)

**Comment by opsecx** [comment]
Fair enough but got most of it set up though, so would be really cool to be able to try it out
